backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'topic_1'
    label: 'Topic 1'
    folder: 'content/topic_1'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: 'false' }
      - { label: 'Hide last modification', name: 'hideLastModified', widget: 'boolean', default: 'true' }
      - { label: "Summary", name: "summary", widget: "text"}
      - { label: 'Tags', name: 'tags', widget: 'list', hint: 'add a comma to list several tags'}
      - { label: 'Body', name: 'body', widget: 'markdown' }